version: '2.0'

services:
  web:
    image: chialab/php-dev:5.6-apache
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_enable=1 remote_autostart=1
    networks:
      - ci-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    networks:
      - ci-network
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    command: mysqld --sql_mode="NO_ENGINE_SUBSTITUTION" --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES UTF8MB4;' --innodb-flush-log-at-trx-commit=0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "your-password"

networks:
  ci-network:
    driver: bridge